algorithm: fixmatch
save_dir: ./saved_models/classic_cv_imb
save_name: fixmatch_crest_imagenet127_lb12810_286_ulbNone_286_0
resume: True
load_path: ./saved_models/classic_cv_imb/fixmatch_crest_imagenet127_lb12810_286_ulbNone_286_0/latest_model.pth
overwrite: True
use_tensorboard: True
epoch: 100
num_train_iter: 250000
num_eval_iter: 2500
num_log_iter: 256
num_labels: 12810
batch_size: 256
eval_batch_size: 256
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
uratio: 2
ema_m: 0.999
crop_ratio: 0.875
img_size: 112
optim: SGD
lr: 0.1
momentum: 0.9
weight_decay: 0.0001
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: resnet50
net_from_name: False
data_dir: ./data
dataset: imagenet127
train_sampler: RandomSampler
num_classes: 127
num_workers: 4
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10144
dist_backend: nccl
gpu: None
include_lb_to_ulb: False
lb_imb_ratio: 286
ulb_imb_ratio: 286
ulb_num_labels: None
imb_algorithm: crest
crest_num_gens: 3
crest_pro_dist_align: False
crest_alpha: 0.7
crest_dist_align_t: 0.5
