algorithm: comatch
save_dir: ./saved_models/usb_audio
save_name: comatch_gtzan_400_0
resume: True
load_path: ./saved_models/usb_audio/comatch_gtzan_400_0/latest_model.pth
overwrite: True
use_tensorboard: True
epoch: 100
num_train_iter: 102400
num_eval_iter: 2048
num_log_iter: 256
num_warmup_iter: 5120
num_labels: 400
batch_size: 8
eval_batch_size: 16
ema_m: 0.0
hard_label: False
p_cutoff: 0.95
contrast_p_cutoff: 0.8
contrast_loss_ratio: 1.0
ulb_loss_ratio: 1.0
proj_size: 64
queue_batch: 128
smoothing_alpha: 0.9
T: 0.2
da_len: 32
uratio: 1
use_cat: False
optim: AdamW
lr: 2e-05
momentum: 0.9
weight_decay: 2e-05
layer_decay: 1.0
amp: False
clip: 0.0
net: wave2vecv2_base
net_from_name: False
data_dir: ./data
dataset: gtzan
train_sampler: RandomSampler
num_classes: 10
num_workers: 4
max_length_seconds: 3.0
sample_rate: 16000
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10069
dist_backend: nccl
gpu: None
use_wandb: False
