algorithm: mixmatch
save_dir: ./saved_models/usb_cv/
save_name: mixmatch_tissuemnist_400_0
resume: True
load_path: ./saved_models/usb_cv//mixmatch_tissuemnist_400_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 200
num_train_iter: 204800
num_log_iter: 256
num_eval_iter: 2048
batch_size: 8
eval_batch_size: 16
num_warmup_iter: 5120
num_labels: 400
uratio: 1
ema_m: 0.0
mixup_alpha: 0.5
T: 0.5
ulb_loss_ratio: 10
unsup_warm_up: 0.4
img_size: 32
crop_ratio: 0.95
optim: AdamW
lr: 5e-05
layer_decay: 0.95
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
use_cat: True
net: vit_tiny_patch2_32
net_from_name: False
data_dir: ./data
dataset: tissuemnist
train_sampler: RandomSampler
num_classes: 8
num_workers: 4
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10039
dist_backend: nccl
gpu: None
use_pretrain: True
pretrain_path: https://github.com/microsoft/Semi-supervised-learning/releases/download/v.0.0.0/vit_tiny_patch2_32_mlp_im_1k_32.pth
