algorithm: remixmatch
save_dir: ./saved_models/classic_cv_imb
save_name: remixmatch_abc_imagenet127_lb12810_286_ulbNone_286_0
resume: True
load_path: ./saved_models/classic_cv_imb/remixmatch_abc_imagenet127_lb12810_286_ulbNone_286_0/latest_model.pth
overwrite: True
use_tensorboard: True
epoch: 200
num_train_iter: 500000
num_eval_iter: 2500
num_log_iter: 256
num_labels: 12810
batch_size: 256
eval_batch_size: 256
mixup_alpha: 0.75
T: 0.5
kl_loss_ratio: 0.5
ulb_loss_ratio: 1.5
rot_loss_ratio: 0.5
unsup_warm_up: 0.015625
uratio: 1
ema_m: 0.999
crop_ratio: 0.875
img_size: 112
optim: SGD
lr: 0.1
momentum: 0.9
weight_decay: 0.0001
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: resnet50
net_from_name: False
data_dir: ./data
dataset: imagenet127
train_sampler: RandomSampler
num_classes: 127
num_workers: 4
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10300
dist_backend: nccl
gpu: None
include_lb_to_ulb: False
lb_imb_ratio: 286
ulb_imb_ratio: 286
ulb_num_labels: None
imb_algorithm: abc
dist_align_target: uniform
abc_p_cutoff: 0.95
abc_loss_ratio: 1.0
