algorithm: mpl
save_dir: ./saved_models/usb_cv
save_name: mpl_stl10_100_0
resume: True
load_path: ./saved_models/usb_cv/mpl_stl10_100_0/latest_model.pth
overwrite: True
use_tensorboard: True
epoch: 200
num_train_iter: 204800
num_eval_iter: 2048
batch_size: 8
eval_batch_size: 16
num_warmup_iter: 5120
num_labels: 100
uratio: 1
ema_m: 0.0
tsa_schedule: none
T: 0.7
p_cutoff: 0.6
ulb_loss_ratio: 8.0
teacher_lr: 0.03
label_smoothing: 0.1
num_uda_warmup_iter: 5000
num_stu_wait_iter: 3000
img_size: 96
crop_ratio: 0.875
optim: AdamW
lr: 5e-05
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
net: vit_base_patch16_96
net_from_name: False
data_dir: ./data
dataset: stl10
train_sampler: RandomSampler
num_classes: 10
num_workers: 4
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10065
dist_backend: nccl
gpu: None
use_pretrain: True
pretrain_path: https://github.com/microsoft/Semi-supervised-learning/mae_pretrain_vit_base.pth
