algorithm: fixmatch
save_dir: ./saved_models/classic_cv_imb
save_name: fixmatch_cossl_stl10_lb150_10_ulbNone_1.0_0
resume: True
load_path: ./saved_models/classic_cv_imb/fixmatch_cossl_stl10_lb150_10_ulbNone_1.0_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 256
num_train_iter: 262144
num_eval_iter: 1024
num_log_iter: 256
num_labels: 150
batch_size: 64
eval_batch_size: 256
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
uratio: 2
ema_m: 0.999
crop_ratio: 0.875
img_size: 32
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: wrn_28_2
net_from_name: False
data_dir: ./data
dataset: stl10
train_sampler: RandomSampler
num_classes: 10
num_workers: 1
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10238
dist_backend: nccl
gpu: None
include_lb_to_ulb: False
lb_imb_ratio: 10
ulb_imb_ratio: 1.0
ulb_num_labels: None
imb_algorithm: cossl
cossl_max_lam: 0.6
cossl_tfe_augment: strong
cossl_tfe_u_ratio: 1
cossl_warm_epoch: 200
cossl_tfe_warm_epoch: 10
cossl_tfe_warm_lr: 0.02
cossl_tfe_warm_ema_decay: 0.999
cossl_tfe_warm_wd: 0.0005
cossl_tfe_warm_bs: 64
