algorithm: fixmatch
save_dir: ./saved_models/classic_cv_imb
save_name: fixmatch_darp_cifar100_lb150_10_ulb300_-10_0
resume: True
load_path: ./saved_models/classic_cv_imb/fixmatch_darp_cifar100_lb150_10_ulb300_-10_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 256
num_train_iter: 262144
num_eval_iter: 1024
num_log_iter: 256
num_labels: 150
batch_size: 64
eval_batch_size: 256
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
uratio: 2
ema_m: 0.999
crop_ratio: 0.875
img_size: 32
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: wrn_28_2
net_from_name: False
data_dir: ./data
dataset: cifar100
train_sampler: RandomSampler
num_classes: 100
num_workers: 1
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10177
dist_backend: nccl
gpu: None
include_lb_to_ulb: False
lb_imb_ratio: 10
ulb_imb_ratio: -10
ulb_num_labels: 300
imb_algorithm: darp
darp_warmup_epochs: 200
darp_alpha: 2.0
darp_num_refine_iter: 10
darp_iter_T: 10
