algorithm: remixmatch
save_dir: ./saved_models/usb_cv/
save_name: remixmatch_adaptiope_615_0
resume: True
load_path: ./saved_models/usb_cv//remixmatch_adaptiope_615_0/latest_model.pth
overwrite: True
use_tensorboard: True
epoch: 20
num_train_iter: 20480
num_log_iter: 512
num_eval_iter: 2048
batch_size: 8
eval_batch_size: 16
num_warmup_iter: 2560
num_labels: 615
uratio: 1
ema_m: 0.0
img_size: 224
crop_ratio: 0.875
optim: AdamW
lr: 0.0005
layer_decay: 0.5
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
use_cat: True
net: vit_small_patch16_224
net_from_name: False
data_dir: ./data
dataset: adaptiope
train_sampler: RandomSampler
num_classes: 123
num_workers: 3
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10028
dist_backend: nccl
gpu: None
use_pretrain: True
pretrain_path: https://github.com/microsoft/Semi-supervised-learning/releases/download/v.0.0.0/vit_small_patch16_224_mlp_im_1k_224.pth
labeled_domain: product_images
unlabeled_domain: real_life
eval_domain: product_images