algorithm: pimodel
save_dir: ./saved_models/usb_audio
save_name: pimodel_fsdnoisy_1773_0
resume: True
load_path: ./saved_models/usb_audio/pimodel_fsdnoisy_1773_0/latest_model.pth
overwrite: True
use_tensorboard: True
epoch: 100
num_train_iter: 102400
num_eval_iter: 2048
num_log_iter: 256
num_warmup_iter: 5120
num_labels: 1773
batch_size: 8
eval_batch_size: 16
ema_m: 0.0
ulb_loss_ratio: 10
unsup_warm_up: 0.4
uratio: 1
use_cat: False
optim: AdamW
lr: 0.0005
momentum: 0.9
weight_decay: 2e-05
layer_decay: 0.75
amp: False
clip: 0.0
net: hubert_base
net_from_name: False
data_dir: ./data
dataset: fsdnoisy
train_sampler: RandomSampler
num_classes: 20
num_workers: 4
max_length_seconds: 5.0
sample_rate: 16000
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10047
dist_backend: nccl
gpu: None
use_wandb: False
