algorithm: pseudolabel
save_dir: ./saved_models/usb_audio
save_name: pseudolabel_urbansound8k_100_0
resume: True
load_path: ./saved_models/usb_audio/pseudolabel_urbansound8k_100_0/latest_model.pth
overwrite: True
use_tensorboard: True
epoch: 100
num_train_iter: 102400
num_eval_iter: 2048
num_log_iter: 256
num_warmup_iter: 5120
num_labels: 100
batch_size: 8
eval_batch_size: 16
ema_m: 0.0
p_cutoff: 0.95
ulb_loss_ratio: 1.0
unsup_warm_up: 0.4
uratio: 1
use_cat: False
optim: AdamW
lr: 5e-05
momentum: 0.9
weight_decay: 2e-05
layer_decay: 0.75
amp: False
clip: 0.0
net: hubert_base
net_from_name: False
data_dir: ./data
dataset: urbansound8k
train_sampler: RandomSampler
num_classes: 10
num_workers: 4
max_length_seconds: 4.0
sample_rate: 16000
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10018
dist_backend: nccl
gpu: None
use_wandb: False
