algorithm: remixmatch
save_dir: ./saved_models/classic_cv_imb
save_name: remixmatch_daso_cifar10_lb1500_100_ulb3000_-100_0
resume: True
load_path: ./saved_models/classic_cv_imb/remixmatch_daso_cifar10_lb1500_100_ulb3000_-100_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 256
num_train_iter: 262144
num_eval_iter: 1024
num_log_iter: 256
num_labels: 1500
batch_size: 64
eval_batch_size: 256
mixup_alpha: 0.75
T: 0.5
kl_loss_ratio: 0.5
ulb_loss_ratio: 1.5
rot_loss_ratio: 0.5
unsup_warm_up: 0.015625
uratio: 1
ema_m: 0.999
crop_ratio: 0.875
img_size: 32
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: wrn_28_2
net_from_name: False
data_dir: ./data
dataset: cifar10
train_sampler: RandomSampler
num_classes: 10
num_workers: 1
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10329
dist_backend: nccl
gpu: None
include_lb_to_ulb: False
lb_imb_ratio: 100
ulb_imb_ratio: -100
ulb_num_labels: 3000
imb_algorithm: daso
dist_align_target: uniform
daso_queue_len: 256
daso_T_proto: 0.05
daso_interp_alpha: 0.5
daso_with_dist_aware: True
daso_assign_loss_ratio: 1.0
daso_num_pl_dist_iter: 100
daso_num_pretrain_iter: 5120
daso_T_dist: 1.5
